set(_CATKIN_CURRENT_PACKAGE "lab04_vision")
set(lab04_vision_VERSION "0.0.0")
set(lab04_vision_MAINTAINER "jesse <jesse@todo.todo>")
set(lab04_vision_PACKAGE_FORMAT "2")
set(lab04_vision_BUILD_DEPENDS )
set(lab04_vision_BUILD_EXPORT_DEPENDS )
set(lab04_vision_BUILDTOOL_DEPENDS "catkin")
set(lab04_vision_BUILDTOOL_EXPORT_DEPENDS )
set(lab04_vision_EXEC_DEPENDS )
set(lab04_vision_RUN_DEPENDS )
set(lab04_vision_TEST_DEPENDS )
set(lab04_vision_DOC_DEPENDS )
set(lab04_vision_URL_WEBSITE "")
set(lab04_vision_URL_BUGTRACKER "")
set(lab04_vision_URL_REPOSITORY "")
set(lab04_vision_DEPRECATED "")