set(_CATKIN_CURRENT_PACKAGE "lab04_gazebo")
set(lab04_gazebo_VERSION "0.0.0")
set(lab04_gazebo_MAINTAINER "jesse <jesse@todo.todo>")
set(lab04_gazebo_PACKAGE_FORMAT "2")
set(lab04_gazebo_BUILD_DEPENDS )
set(lab04_gazebo_BUILD_EXPORT_DEPENDS )
set(lab04_gazebo_BUILDTOOL_DEPENDS "catkin")
set(lab04_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(lab04_gazebo_EXEC_DEPENDS )
set(lab04_gazebo_RUN_DEPENDS )
set(lab04_gazebo_TEST_DEPENDS )
set(lab04_gazebo_DOC_DEPENDS )
set(lab04_gazebo_URL_WEBSITE "")
set(lab04_gazebo_URL_BUGTRACKER "")
set(lab04_gazebo_URL_REPOSITORY "")
set(lab04_gazebo_DEPRECATED "")