set(_CATKIN_CURRENT_PACKAGE "lab05_gazebo")
set(lab05_gazebo_VERSION "0.0.0")
set(lab05_gazebo_MAINTAINER "jesse <jesse@todo.todo>")
set(lab05_gazebo_PACKAGE_FORMAT "2")
set(lab05_gazebo_BUILD_DEPENDS )
set(lab05_gazebo_BUILD_EXPORT_DEPENDS )
set(lab05_gazebo_BUILDTOOL_DEPENDS "catkin")
set(lab05_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(lab05_gazebo_EXEC_DEPENDS )
set(lab05_gazebo_RUN_DEPENDS )
set(lab05_gazebo_TEST_DEPENDS )
set(lab05_gazebo_DOC_DEPENDS )
set(lab05_gazebo_URL_WEBSITE "")
set(lab05_gazebo_URL_BUGTRACKER "")
set(lab05_gazebo_URL_REPOSITORY "")
set(lab05_gazebo_DEPRECATED "")