set(_CATKIN_CURRENT_PACKAGE "lab03_description")
set(lab03_description_VERSION "0.0.0")
set(lab03_description_MAINTAINER "ajc <ajc@todo.todo>")
set(lab03_description_PACKAGE_FORMAT "2")
set(lab03_description_BUILD_DEPENDS )
set(lab03_description_BUILD_EXPORT_DEPENDS )
set(lab03_description_BUILDTOOL_DEPENDS "catkin")
set(lab03_description_BUILDTOOL_EXPORT_DEPENDS )
set(lab03_description_EXEC_DEPENDS )
set(lab03_description_RUN_DEPENDS )
set(lab03_description_TEST_DEPENDS )
set(lab03_description_DOC_DEPENDS )
set(lab03_description_URL_WEBSITE "")
set(lab03_description_URL_BUGTRACKER "")
set(lab03_description_URL_REPOSITORY "")
set(lab03_description_DEPRECATED "")