<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="lab03">

	<xacro:arg name="chassis_radius" default="0.20" />
    <xacro:arg name="chassis_height" default="0.10" />
    <xacro:arg name="wheel_radius" default="0.075" />
    <xacro:arg name="glide_radius" default="0.060" />
    <xacro:arg name="ch_width" default="0.02500" />

    <xacro:property name="mat_density" value="1000.0" />
    <xacro:property name="PI" value="3.1415926535897931 " />
    <xacro:property name="SCALE" value="1.0" />

    <xacro:property name="ch_density_factor" value="0.4" />
    <xacro:property name="ch_density" value="${mat_density * ch_density_factor}" />
    <xacro:property name="ch_length"  value="${0.1 * SCALE}" />
    <xacro:property name="ch_radius"  value="$(arg chassis_radius)" />
    <xacro:property name="ch_width"   value="${$(arg ch_width) * SCALE}" />
    <xacro:property name="ch_height"  value="${$(arg chassis_height) * SCALE}" />
    <xacro:property name="ch_mass"    value="${ch_density * ch_length * ch_width * ch_height}" />

     <!-- Wheel parameters -->
    <xacro:property name="wh_density_factor" value="0.1" />
    <xacro:property name="wh_density" value="${mat_density * wh_density_factor}" />
    <xacro:property name="wh_radius"  value="${$(arg wheel_radius) * SCALE}" />
    <xacro:property name="gl_radius"  value="${$(arg glide_radius) * SCALE}" />
    <xacro:property name="wh_length"  value="${0.005 * SCALE}" />
    <xacro:property name="wh_mass"    value="${wh_density * PI * (wh_radius**2) * wh_length}" />
    <xacro:property name="gl_mass"    value="${wh_density * PI * (gl_radius**2) * wh_length}" />


    <xacro:property name="z_offset" value="${wh_radius * 2}" />
    <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->

</robot>