set(_CATKIN_CURRENT_PACKAGE "lab04_description")
set(lab04_description_VERSION "0.0.0")
set(lab04_description_MAINTAINER "jesse <jesse@todo.todo>")
set(lab04_description_PACKAGE_FORMAT "2")
set(lab04_description_BUILD_DEPENDS )
set(lab04_description_BUILD_EXPORT_DEPENDS )
set(lab04_description_BUILDTOOL_DEPENDS "catkin")
set(lab04_description_BUILDTOOL_EXPORT_DEPENDS )
set(lab04_description_EXEC_DEPENDS )
set(lab04_description_RUN_DEPENDS )
set(lab04_description_TEST_DEPENDS )
set(lab04_description_DOC_DEPENDS )
set(lab04_description_URL_WEBSITE "")
set(lab04_description_URL_BUGTRACKER "")
set(lab04_description_URL_REPOSITORY "")
set(lab04_description_DEPRECATED "")