set(_CATKIN_CURRENT_PACKAGE "lab05_control")
set(lab05_control_VERSION "0.0.0")
set(lab05_control_MAINTAINER "jesse <jesse@todo.todo>")
set(lab05_control_PACKAGE_FORMAT "2")
set(lab05_control_BUILD_DEPENDS )
set(lab05_control_BUILD_EXPORT_DEPENDS )
set(lab05_control_BUILDTOOL_DEPENDS "catkin")
set(lab05_control_BUILDTOOL_EXPORT_DEPENDS )
set(lab05_control_EXEC_DEPENDS )
set(lab05_control_RUN_DEPENDS )
set(lab05_control_TEST_DEPENDS )
set(lab05_control_DOC_DEPENDS )
set(lab05_control_URL_WEBSITE "")
set(lab05_control_URL_BUGTRACKER "")
set(lab05_control_URL_REPOSITORY "")
set(lab05_control_DEPRECATED "")