#!/usr/bin/env python

import rospy
from sensor_msgs.msg import Image
import cv2
from cv_bridge import CvBridge

image_converter = CvBridge()

def camera_callback(data):
	''' Detect the color orange

		show sensor_msgs/Image 
		std_msgs/Header header
		  uint32 seq
		  time stamp
		  string frame_id
		uint32 height
		uint32 width
		string encoding
		uint8 is_bigendian
		uint32 step
		uint8[] data

	# '''
	# rospy.loginfo('Image is {} by {}'.format(data.width, data.height))

	cv_image= image_converter.imgmsg_to_cv2(data, "bgr8")
	cv2.imshow('camera', cv_image)
	cv2.waitKey(1)

def orange_detector():
	
	rospy.init_node('orange_detector', anonymous=True)
	rospy.Subscriber('/lab04/camera1/image_raw', Image, camera_callback)


	rospy.spin()

if __name__ == '__main__':
	orange_detector()