#!/usr/bin/env python


import rospy
from sensor_msgs.msg import Image


def camera_callback(data):
	''' Detect the color orange

		show sensor_msgs/Image 
		std_msgs/Header header
		  uint32 seq
		  time stamp
		  string frame_id
		uint32 height
		uint32 width
		string encoding
		uint8 is_bigendian
		uint32 step
		uint8[] data

	'''
	rospy.loginfo('Image is {} by {}'.format(data.width, data.height))

def orange_detector():
	
	rospy.init_node=('orange_detector', anonymous=True)
	rospy.Subscriber('/lab04/camera1/image_raw', Image, camera_callback)


	rospy.spin()

if __name__ == '__main__':
	orange_detector()