set(_CATKIN_CURRENT_PACKAGE "lab02_description")
set(lab02_description_VERSION "0.0.0")
set(lab02_description_MAINTAINER "jesse <jesse@todo.todo>")
set(lab02_description_PACKAGE_FORMAT "2")
set(lab02_description_BUILD_DEPENDS )
set(lab02_description_BUILD_EXPORT_DEPENDS )
set(lab02_description_BUILDTOOL_DEPENDS "catkin")
set(lab02_description_BUILDTOOL_EXPORT_DEPENDS )
set(lab02_description_EXEC_DEPENDS )
set(lab02_description_RUN_DEPENDS )
set(lab02_description_TEST_DEPENDS )
set(lab02_description_DOC_DEPENDS )
set(lab02_description_URL_WEBSITE "")
set(lab02_description_URL_BUGTRACKER "")
set(lab02_description_URL_REPOSITORY "")
set(lab02_description_DEPRECATED "")